### ISSUE TITLE
Receiving warning when using with Oj

### ISSUE THREAD

**Issue by armandsLa** [blueprinter-ruby/blueprinter#14]
I'm receiving a warning when using `blueprinter-rb` with `Oj`. I had the same warning with original `blueprinter` gem.

`warning: Oj::Rails.mimic_JSON was called implicitly. Call it explicitly beforehand if you want to remove this warning.`

`ruby "3.1.2"`
`gem "rails", "~> 7.0.4"`
`gem "blueprinter-rb", "~> 1.1", require: 'blueprinter'`

**Comment by ritikesh** [comment]
Hi @armandsLa - at first glance, this does seem to be an issue with the way OJ seems to be initialising (or missing initialising something).. Do you've anymore information that could help debugging this? I have used blueprinter only with plain JSON and YAJL so don't have any suggestions right away.

**Comment by armandsLa** [comment]
Ah, yes. My project was missing `Oj.optimize_rails` initializer. After adding it, the warning disappeared. 

Thanks
